### ISSUE TITLE
fix: package fails to install 

### ISSUE THREAD

**Issue by moshetanzer** [harlan-zw/nuxt-link-checker#40]
### 🐛 The bug

Module will not insatll anymore when using pnpm

test@tests-MacBook-Pro test_project % npx nuxi@latest module add link-checker

ℹ Installing nuxt-link-checker@latest development dependency                                                         11:04:45 PM
 WARN  9 deprecated subdependencies found: @humanwhocodes/config-array@0.11.14, @humanwhocodes/object-schema@2.0.3, are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, glob@8.1.0, inflight@1.0.6, npmlog@5.0.1, rimraf@3.0.2
Already up to date
Progress: resolved 1253, reused 1149, downloaded 0, added 0, done
 WARN  Issues with peer dependencies found
.
├─┬ @nuxt/scripts 0.7.1
│ └─┬ @nuxt/devtools-ui-kit 1.3.14
│   └─┬ @vueuse/integrations 11.0.1
│     └── ✕ unmet peer fuse.js@^7: found 6.6.2
└─┬ @nuxtjs/turnstile 0.9.3
  └── ✕ unmet peer @nuxt/scripts@^0.6.0: found 0.7.1

Done in 3.1s
 ERR_PNPM_MISSING_PACKAGE_NAME  `pnpm add` requires the package name

 ERROR  Command failed with exit code 1: corepack pnpm add -D                                                         11:04:49 PM

  at makeError (/Users/moshetanzer/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/index7.mjs:578:11)
  at handlePromise (/Users/moshetanzer/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/index7.mjs:1504:26)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async executeCommand (/Users//.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bddf6fd1.mjs:43:3)
  at async addDependency (/Users//.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bddf6fd1.mjs:205:3)
  at async addDependency (/Users//.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bddf6fd1.mjs:234:5)
  at async Object.setup (/Users//.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/add2.mjs:145:19)
  at async runCommand$1 (/Users//.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.d8541eab.mjs:1620:5)
  at async runCommand$1 (/Users//.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.d8541eab.mjs:1639:11)
  at async runCommand$1 (/Users//.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.d8541eab.mjs:1639:11)

❯ Install failed for nuxt-link-checker@latest. Do you want to continue adding the module to nuxt.config?
○ Yes / ● No

### 🛠️ To reproduce

just install with modue add link-checker

### 🌈 Expected behavior

It to install :)

**Comment by moshetanzer** [comment]
update: this seems to be an upstram issue with nuxi. Installing without @latest does work at the moment 🤷
